# Generated by Django 2.1.7 on 2019-09-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('chargeperkm', models.IntegerField()),
                ('profileurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderticket', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('emailid', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('chargeperkm', models.IntegerField()),
                ('profileurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User'),
        ),
        migrations.AddField(
            model_name='orders',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Drivers'),
        ),
    ]
