# Generated by Django 2.1.7 on 2019-09-08 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
    atomic = False
