# Generated by Django 2.1.7 on 2019-09-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190908_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
    atomic = False
