# Generated by Django 2.2.5 on 2019-09-15 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enddate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 15, 10, 40, 33, 88150, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='triptype',
            field=models.CharField(default='round', max_length=50),
            preserve_default=False,
        ),
    ]
